Update webpack et al
IronCoreLabs/recrypt-wasm-binding pull request #115
Opened 2024-08-26 22:35 UTC by skeet70

In service of getting an updated version of `micromatch` for a stupid vulnerability that will never affect us.

2024-08-26 23:03 UTC, skeet70 commented
The change to remove `wasm-bindgen`'s serde feature is because of https://rustwasm.github.io/wasm-bindgen/reference/arbitrary-data-with-serde.html#history.

2024-09-06 16:59 UTC, giarc3 requested changes
What's the new `wasm-bindgen-Cargo.lock` for? 

Also, would it be okay for us to update `puppeteer` to `"^22.8.2"`? We're ~4 years behind and it won't run tests for me locally without updating it

2024-09-06 19:47 UTC, skeet70 commented
`wasm-bindgen-Cargo.lock` was used in the `flake.nix` so it could install bindgen from source, but I don't think it's necessary now. I don't have a problem with someone updating puppeteer, whether in this PR or another. This PR was to get past a CVE (that didn't actually matter).

2024-09-06 19:56 UTC, giarc3 approved these changes

2024-09-09 15:08 UTC, merged