Removed fixBindgen script and MS Edge Legacy support
IronCoreLabs/recrypt-wasm-binding pull request #45
Opened 2021-06-01 16:36 UTC by clintfred

See #43 

* `setRandomSeed` only existed to support MS Edge Legacy. Since this browser is no longer supported by MS, support is being removed.
* Given the removal of `setRandomSeed` and the latest wasm-bindgen, fixBindgen is no longer needed.

2021-06-01 21:24 UTC, BobWall23 approved these changes

2021-06-01 22:27 UTC, coltfred requested changes
@clintfred I think you still need to remove setRandomSeed from the types file in recrypt_wasm_binding.d.ts

2021-06-01 23:01 UTC, coltfred approved these changes

2021-06-02 17:30 UTC, giarc3 approved these changes

2021-06-02 17:51 UTC, skeet70 approved these changes

2021-06-02 21:16 UTC, merged